/**
 * Keywords and patterns for BrainService
 * Extracted from BrainService.js to improve maintainability
 */

module.exports = {
  // Important keywords for Indonesian customer service context
  importantKeywords: [
    "harga",
    "berapa",
    "biaya",
    "tarif",
    "price",
    "ada",
    "tersedia",
    "ready",
    "stock",
    "available",
    "netflix",
    "spotify",
    "youtube",
    "disney",
    "canva",
    "vidio",
    "bayar",
    "pembayaran",
    "transfer",
    "dana",
    "ovo",
    "gopay",
    "bantuan",
    "bantu",
    "help",
    "tolong",
    "hai",
    "halo",
    "hello",
    "hi",
    "terima kasih",
    "makasih",
    "thanks",
    "bye"
  ],

  // Common entities for product matching
  commonEntities: [
    "netflix",
    "spotify",
    "youtube",
    "disney",
    "canva",
    "vidio",
    "amazon",
    "hbo",
    "game pass",
    "chatgpt",
    "loklok",
    "prime",
    "viu",
    "wetv"
  ],

  // Topic keywords map for context similarity
  topicKeywordsMap: {
    streaming: [
      "netflix",
      "spotify",
      "youtube",
      "disney",
      "vidio",
      "film",
      "musik",
      "lagu",
      "nonton",
      "dengar",
    ],
    payment: [
      "bayar",
      "pembayaran",
      "transfer",
      "dana",
      "ovo",
      "gopay",
      "qris",
      "bank",
      "bca",
      "mandiri",
    ],
    technical: [
      "error",
      "masalah",
      "problem",
      "gagal",
      "tidak bisa",
      "bug",
      "crash",
      "loading",
      "lambat",
      "reset",
    ],
    account: [
      "akun",
      "password",
      "kata sandi",
      "login",
      "masuk",
      "daftar",
      "register",
      "email",
      "username",
      "profil",
    ],
    support: [
      "bantuan",
      "help",
      "tolong",
      "customer service",
      "cs",
      "kontak",
      "hubungi",
      "tanya",
      "info",
      "informasi",
    ],
  },

  // Related intents map for intent similarity
  relatedIntentsMap: {
    price_inquiry: ["payment", "available"],
    payment: ["price_inquiry", "refund_policy"],
    help: ["technical_details", "refund_policy"],
    available: ["price_inquiry", "technical_details"],
    refund_policy: ["payment", "help"],
    technical_details: ["help", "available"],
    referral_loyalty: ["price_inquiry", "emerging_services"],
    emerging_services: ["referral_loyalty", "technical_details"],
  },

  // Indonesian positive sentiment words
  positiveWords: [
    // General positive words
    "bagus",
    "baik",
    "hebat",
    "keren",
    "mantap",
    "mantab",
    "mantul",
    "oke",
    "ok",
    "sip",
    "top",
    "senang",
    "gembira",
    "bahagia",
    "puas",
    "sukses",
    "berhasil",
    "luar biasa",
    "wow",
    "kece",
    "cakep",
    "cantik",
    "ganteng",
    "indah",
    "menarik",
    "menyenangkan",
    "ramah",
    "sopan",
    "cepat",
    "mudah",
    "praktis",
    "efisien",
    "efektif",
    "berguna",
    "bermanfaat",
    "membantu",
    "suka",
    "cinta",
    "sayang",
    "setuju",
    "benar",
    "tepat",
    "akurat",
    "lengkap",
    "sempurna",

    // Customer service specific
    "terima kasih",
    "makasih",
    "thanks",
    "thx",
    "tq",
    "recommended",
    "rekomen",
    "rekomendasi",
    "lancar",
    "cepat",
    "responsif",
    "informatif",
    "jelas",
    "murah",
    "terjangkau",
    "worth it",
    "worth",
    "puas",
    "kepuasan",
    "satisfied",
    "memuaskan",
    "terpercaya",
    "amanah",
    "jujur",
    "profesional",
    "handal",
    "reliable",
    "berkualitas",
    "quality",
    "premium",
    "original",
    "asli",
    "berhasil",
    "sukses",
    "success",
    "beruntung",
    "lucky",
    "promo",
    "diskon",
    "hemat",
    "bonus",
  ],

  // Indonesian negative sentiment words
  negativeWords: [
    // General negative words
    "buruk",
    "jelek",
    "rusak",
    "busuk",
    "hancur",
    "parah",
    "payah",
    "lemah",
    "lambat",
    "lelet",
    "mahal",
    "kemahalan",
    "boros",
    "rugi",
    "kecewa",
    "sedih",
    "marah",
    "kesal",
    "jengkel",
    "benci",
    "bete",
    "bt",
    "sebel",
    "sebal",
    "bosan",
    "bodo",
    "bodoh",
    "tolol",
    "goblok",
    "gagal",
    "salah",
    "error",
    "eror",
    "cacat",
    "kurang",
    "tidak",
    "tak",
    "ga",
    "gak",
    "nggak",
    "ngga",
    "bukan",
    "jangan",
    "males",
    "malas",
    "susah",
    "sulit",
    "rumit",
    "ribet",
    "repot",

    // Customer service specific
    "komplain",
    "complaint",
    "keluhan",
    "protes",
    "refund",
    "pengembalian",
    "batal",
    "cancel",
    "tipu",
    "bohong",
    "scam",
    "penipu",
    "nipu",
    "lama",
    "lambat",
    "telat",
    "delay",
    "pending",
    "tidak respon",
    "tidak responsif",
    "tidak profesional",
    "tidak jelas",
    "tidak akurat",
    "tidak sesuai",
    "tidak berfungsi",
    "tidak bisa",
    "tidak dapat",
    "tidak valid",
    "tidak cocok",
    "tidak worth it",
    "tidak puas",
    "tidak bagus",
    "tidak baik",
    "tidak recommended",
    "jangan",
    "berhenti",
    "stop",
    "buang waktu",
    "buang uang",
    "sia-sia",
  ],

  // Intent extraction patterns
  intentPatterns: {
    price_inquiry: /\b(harga|berapa|biaya|tarif)\b/,
    availability: /\b(ada|tersedia|ready|stock|masih)\b/,
    payment: /\b(bayar|pembayaran|transfer|dana|ovo|gopay)\b/,
    help: /\b(bantuan|bantu|help|tolong)\b/,
    greeting: /\b(hai|halo|selamat|pagi|siang|sore|malam)\b/,
    goodbye: /\b(terima kasih|makasih|thanks|bye)\b/
  },

  // English marker words for language detection
  englishMarkers: [
    "the",
    "a",
    "an",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "shall",
    "should",
    "may",
    "might",
    "must",
    "can",
    "could",
    "i",
    "you",
    "he",
    "she",
    "it",
    "we",
    "they",
    "me",
    "him",
    "her",
    "us",
    "them",
    "my",
    "your",
    "his",
    "its",
    "our",
    "their",
    "mine",
    "yours",
    "hers",
    "ours",
    "theirs",
    "this",
    "that",
    "these",
    "those",
    "what",
    "which",
    "who",
    "whom",
    "whose",
    "when",
    "where",
    "why",
    "how",
  ],

  // Fallback responses by intent
  fallbackResponses: {
    greeting: [
      "Halo! Selamat datang di layanan kami. Ada yang bisa saya bantu hari ini?",
      "Hai! Senang bertemu dengan Anda. Bagaimana saya bisa membantu?",
      "Selamat datang! Saya siap membantu Anda dengan pertanyaan seputar layanan kami.",
    ],
    price_inquiry: [
      "Untuk informasi harga yang akurat, mohon sebutkan layanan spesifik yang Anda minati. Kami memiliki berbagai paket dengan harga yang kompetitif.",
      "Saya akan senang membantu dengan informasi harga. Bisakah Anda memberitahu layanan mana yang ingin Anda ketahui harganya?",
      "Harga layanan kami bervariasi tergantung paket yang dipilih. Mohon sebutkan layanan yang Anda cari untuk informasi lebih detail.",
    ],
    available: [
      "Untuk mengecek ketersediaan, mohon sebutkan layanan atau produk spesifik yang Anda cari.",
      "Saya dapat membantu mengecek ketersediaan. Layanan apa yang ingin Anda ketahui statusnya?",
      "Ketersediaan layanan dapat berbeda-beda. Mohon sebutkan layanan yang Anda minati untuk pengecekan yang akurat.",
    ],
    payment: [
      "Kami menerima berbagai metode pembayaran. Untuk informasi lebih detail tentang pembayaran, mohon sebutkan layanan yang ingin Anda beli.",
      "Sistem pembayaran kami aman dan mudah. Ada metode pembayaran tertentu yang ingin Anda ketahui?",
      "Proses pembayaran sangat mudah dan aman. Bisakah Anda memberitahu layanan mana yang ingin Anda beli?",
    ],
    help: [
      "Saya di sini untuk membantu Anda! Bisakah Anda menjelaskan lebih detail masalah atau pertanyaan yang Anda hadapi?",
      "Tentu saja saya akan membantu. Mohon jelaskan lebih spesifik apa yang Anda butuhkan.",
      "Saya siap membantu menyelesaikan masalah Anda. Bisa dijelaskan lebih detail situasinya?",
    ],
    goodbye: [
      "Terima kasih telah menggunakan layanan kami! Jangan ragu untuk kembali jika ada pertanyaan lain.",
      "Sampai jumpa! Semoga hari Anda menyenangkan. Kami selalu siap membantu kapan saja.",
      "Terima kasih! Jika ada yang perlu dibantu lagi, jangan sungkan untuk menghubungi kami.",
    ],
    default: [
      "Maaf, saya belum sepenuhnya memahami pertanyaan Anda. Bisakah Anda menjelaskan lebih detail atau menggunakan kata-kata yang berbeda?",
      "Saya ingin membantu Anda dengan sebaik-baiknya. Mohon berikan informasi lebih spesifik tentang apa yang Anda cari.",
      "Untuk memberikan jawaban yang tepat, saya memerlukan informasi lebih detail. Bisakah Anda menjelaskan pertanyaan Anda dengan cara lain?",
    ]
  }
};